[package]
name = "arcane"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = ["crates/*"]

[dependencies]
arcane-internal = { path = "crates/arcane_internal" }

[[example]]
name = "triangle"
path = "examples/triangle.rs"
